language: python
python:
  - 3.3
  - 3.2
  - 2.7
  - 2.6
matrix:
  allow_failures:
    - python: 3.2
virtualenv:
  # This allows installing PyQt using apt-get and being able to import it.
  system_site_packages: true
before_install:
  # On Python 2.7 we install PyQt4 and run the UI tests.
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then source .travis_before_install; fi
install:
  - pip install nose
  - if python --version 2>&1 | grep -v "Python 3." >/dev/null; then pip install unittest2 ; fi
  - pip install cython
  - if python --version 2>&1 | grep "Python 3." >/dev/null; then pip install numpy ; fi
  - python setup.py install
before_script:
  - cd ../..
script:
  - nosetests traits --exe
notifications:
  email:
    - hack@delley.net

