language: python
python:
  - 3.3
  - 3.2
  - 2.7
  - 2.6
install:
  - pip install nose
  - if python --version 2>&1 | grep -v "Python 3." >/dev/null; then pip install unittest2 ; fi
  - pip install cython
  - if python --version 2>&1 | grep "Python 3." >/dev/null; then pip install numpy ; fi
  - python setup.py install
before_script:
  - cd ../..
script:
  - nosetests traits --exe
notifications:
  email:
    - hack@delley.net

